package com.redvethomas.labsql.model;

public enum Genre {
    LITERARY_FICTION, MYSTERY, THRILLER,
    HORROR, HISTORICAL, ROMANCE, WESTERN,
    SPECULATIVE_FICTION, SCIENCE_FICTION,
    FANTASY, DYSTOPIAN, MAGICAL_REALISM, REALIST_LITERATURE;
}
